export interface ProductCare {
  light: string
  water: string
  humidity: string
  temperature: string
  soil: string
}

export interface Product {
  id: number
  name: string
  category: string
  price: number // Numeric for sorting and math calculations (INR Rupees)
  rating: number
  reviews: number
  image: string
  description: string
  details: ProductCare
  sizes: string[]
  careInstructions: string[]
  scientificName?: string
  height?: string
  difficulty?: string
  petFriendly?: string
  airPurifying?: string
}

export const allProducts: Product[] = [
  {
    id: 1,
    name: 'Monstera Deliciosa',
    scientificName: 'Monstera deliciosa',
    category: 'Indoor Plants',
    price: 1250,
    rating: 4.8,
    reviews: 125,
    image: '/images/plants/monstera-plant.jpg?v=2',
    description: 'A tropical beauty known for its iconic split leaves. Perfect for modern interiors and improves air quality.',
    details: {
      light: 'Bright, indirect light',
      water: 'Moderate',
      humidity: 'Moderate to high',
      temperature: '65-75°F',
      soil: 'Well-draining potting soil',
    },
    sizes: ['Small (6-8 inch)', 'Medium (10-12 inch)', 'Large (14-16 inch)'],
    careInstructions: [
      'Check Soil: Check if the top 2 inches of soil are dry.',
      'Water: Water thoroughly until water drains out. (Watering Frequency: Once every 7-10 days).',
      'Drain: Ensure excess water drains completely.',
      'Observe: Place in the right light and observe growth.',
      'Repeat: Repeat the cycle and watch it thrive.',
    ],
    height: '1.5 – 2.5 ft',
    difficulty: 'Easy',
    petFriendly: 'Yes',
    airPurifying: 'High',
  },
  {
    id: 2,
    name: 'Peace Lily',
    scientificName: 'Spathiphyllum',
    category: 'Indoor Plants',
    price: 850,
    rating: 4.9,
    reviews: 156,
    image: '/images/plants/peace-lily.jpg?v=2',
    description: 'Peace Lilies are famous for their air-purifying abilities and elegant white blooms. They are resilient, low-maintenance plants that tell you when they are thirsty.',
    details: {
      light: 'Low to medium light',
      water: 'Keep soil consistently moist',
      humidity: 'High humidity preferred',
      temperature: '60-80°F',
      soil: 'Peat-rich, well-draining soil',
    },
    sizes: ['Small (5-7 inch)', 'Medium (8-10 inch)'],
    careInstructions: [
      'Water when leaves begin to droop slightly',
      'Keep away from direct sunlight to avoid leaf burn',
      'Mist the leaves regularly to maintain humidity',
      'Prune yellow or brown leaves at the base',
    ],
    height: '1.0 – 1.5 ft',
    difficulty: 'Easy',
    petFriendly: 'No',
    airPurifying: 'High',
  },
  {
    id: 3,
    name: 'Pothos Hanging',
    scientificName: 'Epipremnum aureum',
    category: 'Indoor Plants',
    price: 399,
    rating: 4.7,
    reviews: 92,
    image: '/images/plants/pothos-hanging.jpg',
    description: 'Pothos is one of the easiest house plants to grow. Its beautiful trailing vines look stunning cascading from hanging baskets or shelves, featuring heart-shaped leaves.',
    details: {
      light: 'Low to bright, indirect light',
      water: 'Water when top 2 inches of soil are dry',
      humidity: 'Average indoor humidity',
      temperature: '60-85°F',
      soil: 'Standard potting mix',
    },
    sizes: ['Small basket (6 inch)', 'Medium basket (8 inch)'],
    careInstructions: [
      'Allow soil to dry out between waterings to prevent root rot',
      'Trim vines to encourage fuller growth at the top',
      'Can survive in low light, but variegated patterns fade',
      'Propagates easily in water from stem cuttings',
    ],
    height: '1.5 – 3.0 ft (Trails up to 10 ft)',
    difficulty: 'Easy',
    petFriendly: 'No',
    airPurifying: 'High',
  },
  {
    id: 4,
    name: 'Succulent Collection',
    scientificName: 'Echeveria & Sedum Mix',
    category: 'Outdoor Plants',
    price: 299,
    rating: 4.9,
    reviews: 203,
    image: '/images/plants/succulent-collection.jpg',
    description: 'A curated collection of beautiful, hardy succulents. Perfect for sunny windowsills, desktops, or as a lovely gift. These desert natives store water in their leaves and require very little care.',
    details: {
      light: 'Direct, bright sunlight',
      water: 'Water sparingly, only when completely dry',
      humidity: 'Low/dry air',
      temperature: '55-80°F',
      soil: 'Cactus/Succulent sandy mix',
    },
    sizes: ['Set of 3 (2 inch pots)', 'Set of 6 (2 inch pots)'],
    careInstructions: [
      'Water using the soak and dry method; do not let water sit in the tray',
      'Provide at least 6 hours of bright sunlight daily',
      'Ensure pots have drainage holes',
      'Protect from freezing temperatures',
    ],
    height: '0.2 – 0.5 ft',
    difficulty: 'Easy',
    petFriendly: 'Yes',
    airPurifying: 'Moderate',
  },
  {
    id: 5,
    name: 'Red Roses Bouquet',
    scientificName: 'Rosa rubiginosa',
    category: 'Flower Plants',
    price: 699,
    rating: 4.8,
    reviews: 178,
    image: '/images/plants/rose-flowers.jpg',
    description: 'A classic and stunning arrangement of premium long-stemmed red roses. Perfect for celebrating special occasions, anniversaries, or expressing love. Freshly cut and arranged with elegant greenery.',
    details: {
      light: 'Bright room, avoid direct hot sun',
      water: 'Keep vase water clean and cool',
      humidity: 'Moderate',
      temperature: '60-70°F',
      soil: 'Cut flowers (N/A)',
    },
    sizes: ['Standard (12 stems)', 'Premium (24 stems)'],
    careInstructions: [
      'Trim stems at a 45-degree angle before placing in water',
      'Change water every 2 days and add flower food',
      'Remove any leaves that fall below the water line',
      'Keep away from drafts, direct heat, and ripening fruit',
    ],
    height: '1.2 – 1.8 ft',
    difficulty: 'Medium',
    petFriendly: 'No',
    airPurifying: 'None',
  },
  {
    id: 6,
    name: 'Lavender Plant',
    scientificName: 'Lavandula angustifolia',
    category: 'Flower Plants',
    price: 499,
    rating: 4.6,
    reviews: 67,
    image: '/images/plants/lavender-plant.jpg',
    description: 'Lavender is beloved for its beautiful purple blooms and relaxing, aromatic fragrance. Excellent for herb gardens, sunny patios, or placing near windows to enjoy its calming scent.',
    details: {
      light: 'Full, direct sun (6+ hours)',
      water: 'Water deeply but infrequently; drought-tolerant',
      humidity: 'Low humidity',
      temperature: '50-80°F',
      soil: 'Well-draining, alkaline soil',
    },
    sizes: ['Medium (6 inch pot)', 'Large (8 inch pot)'],
    careInstructions: [
      'Avoid overwatering; let soil dry completely between waterings',
      'Prune in early spring to maintain shape and promote blooms',
      'Ensure excellent drainage to prevent root rot',
      'Harvest flowers just as they start to open for the best fragrance',
    ],
    height: '1.0 – 2.0 ft',
    difficulty: 'Medium',
    petFriendly: 'No',
    airPurifying: 'Low',
  },
  {
    id: 7,
    name: 'Orchid Flower',
    scientificName: 'Phalaenopsis',
    category: 'Flower Plants',
    price: 999,
    rating: 4.7,
    reviews: 145,
    image: '/images/plants/orchid-flower.jpg',
    description: 'Exotic and elegant, this Phalaenopsis orchid displays stunning moth-like blooms that can last for months. A perfect statement piece for dining tables or office desks.',
    details: {
      light: 'Bright, indirect light',
      water: 'Water every 7-10 days, allowing bark to dry',
      humidity: 'High humidity (50-70%)',
      temperature: '65-80°F',
      soil: 'Sphagnum moss or orchid bark mix',
    },
    sizes: ['Standard (Single Spike)', 'Premium (Double Spike)'],
    careInstructions: [
      'Do not let the roots sit in standing water',
      'Mist the air around the orchid or use a humidity tray',
      'Fertilize weekly at weak strength during active growth',
      'Cut the spike back to a node once blooms fade to encourage reblooming',
    ],
    height: '1.2 – 2.2 ft',
    difficulty: 'Medium',
    petFriendly: 'Yes',
    airPurifying: 'Moderate',
  },
  {
    id: 8,
    name: 'Bonsai Tree',
    scientificName: 'Juniperus procumbens',
    category: 'Outdoor Plants',
    price: 2499,
    rating: 4.8,
    reviews: 89,
    image: '/images/plants/bonsai-tree.jpg',
    description: 'A beautiful miniature Juniper Bonsai tree, carefully shaped to represent harmony and balance. An ancient art form that brings peace and mindful energy to any living space.',
    details: {
      light: 'Bright, indirect light; thrives outdoors too',
      water: 'Keep soil moist; do not let dry out completely',
      humidity: 'Moderate to high',
      temperature: '50-75°F',
      soil: 'Special Bonsai fast-draining soil mix',
    },
    sizes: ['Small (5 years old)', 'Medium (8 years old)'],
    careInstructions: [
      'Check moisture daily; water thoroughly when top soil feels dry',
      'Prune new growth regularly to maintain the bonsai shape',
      'Repot every 2-3 years in late spring',
      'Provide outdoor fresh air occasionally if kept indoors',
    ],
    height: '0.8 – 1.5 ft',
    difficulty: 'Hard',
    petFriendly: 'No',
    airPurifying: 'Low',
  },
  {
    id: 9,
    name: 'Tulips Bouquet',
    scientificName: 'Tulipa',
    category: 'Flower Plants',
    price: 899,
    rating: 4.9,
    reviews: 234,
    image: '/images/plants/tulips-bouquet.jpg',
    description: 'A colorful and vibrant arrangement of fresh spring tulips. Symbolizing cheerfulness and renewal, this bouquet brings instant brightness and joy to any room.',
    details: {
      light: 'Bright room, avoid direct sun',
      water: 'Keep vase water clean and cool',
      humidity: 'Average',
      temperature: '55-65°F',
      soil: 'Cut flowers (N/A)',
    },
    sizes: ['Bouquet of 15', 'Bouquet of 30'],
    careInstructions: [
      'Trim stems slightly and place in cold water immediately',
      'Change water daily to keep flowers fresh',
      'Tulips continue to grow in the vase; trim again if they get too tall',
      'Keep away from warm appliances and direct sunlight',
    ],
    height: '1.0 – 1.4 ft',
    difficulty: 'Easy',
    petFriendly: 'No',
    airPurifying: 'None',
  },
  {
    id: 10,
    name: 'Sunflower Garden',
    scientificName: 'Helianthus annuus',
    category: 'Flower Plants',
    price: 399,
    rating: 4.6,
    reviews: 76,
    image: '/images/plants/sunflower-garden.jpg',
    description: 'Bring the joy of summer indoors with these dwarf potted sunflowers. Featuring bright, cheerful yellow petals, they are guaranteed to make anyone smile.',
    details: {
      light: 'Full, direct sun (6-8 hours)',
      water: 'Water daily or when top soil feels dry',
      humidity: 'Average',
      temperature: '60-80°F',
      soil: 'Rich, well-draining compost',
    },
    sizes: ['Single Pot (6 inch)', 'Triple Pot Set'],
    careInstructions: [
      'Place in the sunniest window available',
      'Water at the base of the plant to avoid wet foliage',
      'Stake the stems if they start leaning towards the light',
      'Remove spent blooms to encourage new buds',
    ],
    height: '1.0 – 1.8 ft',
    difficulty: 'Easy',
    petFriendly: 'Yes',
    airPurifying: 'Low',
  },
  {
    id: 11,
    name: 'Dahlia Bouquet',
    scientificName: 'Dahlia pinnata',
    category: 'Flower Plants',
    price: 799,
    rating: 4.7,
    reviews: 110,
    image: '/images/plants/dahlia-bouquet.jpg',
    description: 'A breathtaking bouquet of mixed dahlias, featuring intricate petal patterns and a rich spectrum of colors. Hand-picked and styled to create an exquisite centerpiece.',
    details: {
      light: 'Bright indirect light',
      water: 'Change vase water every 2 days',
      humidity: 'Moderate',
      temperature: '60-70°F',
      soil: 'Cut flowers (N/A)',
    },
    sizes: ['Standard Bouquet', 'Deluxe Bouquet'],
    careInstructions: [
      'Recut stems under water before putting in a clean vase',
      'Keep in a cool spot away from drafts',
      'Add floral preservative to the water',
      'Remove any wilted petals immediately',
    ],
    height: '1.2 – 1.6 ft',
    difficulty: 'Easy',
    petFriendly: 'No',
    airPurifying: 'None',
  },
  {
    id: 12,
    name: 'Premium Orchid',
    scientificName: 'Cymbidium',
    category: 'Flower Plants',
    price: 1599,
    rating: 4.8,
    reviews: 98,
    image: '/images/plants/orchid-flower.jpg',
    description: 'An exquisite premium orchid selection featuring rare color patterns and exceptionally large blooms. Ideal for luxury gifting or as an upscale home decor addition.',
    details: {
      light: 'Filter bright, indirect light',
      water: 'Water weekly when roots look silver/grey',
      humidity: 'High (60%+)',
      temperature: '65-75°F',
      soil: 'Premium orchid bark medium',
    },
    sizes: ['Deluxe Single Spike', 'Grand Double Spike'],
    careInstructions: [
      'Ensure good air circulation around the roots',
      'Water by running water through the pot for 1 minute, then drain',
      'Use a specialized orchid fertilizer monthly',
      'Do not mist flowers directly to avoid spotting',
    ],
    height: '1.5 – 2.5 ft',
    difficulty: 'Medium',
    petFriendly: 'Yes',
    airPurifying: 'Moderate',
  },
  {
    id: 13,
    name: 'Areca Palm',
    scientificName: 'Dypsis lutescens',
    category: 'Indoor Plants',
    price: 950,
    rating: 4.8,
    reviews: 112,
    image: '/images/plants/areca-palm.jpg?v=2',
    description: 'A popular indoor palm known for its air-purifying qualities and feathery, upright fronds. Adds a touch of tropical elegance and freshness to any space.',
    details: {
      light: 'Bright, indirect light',
      water: 'Moderate',
      humidity: 'High',
      temperature: '65-75°F',
      soil: 'Well-draining, slightly acidic soil',
    },
    sizes: ['Medium (2-3 ft)', 'Large (4-5 ft)'],
    careInstructions: [
      'Keep soil moist but never waterlogged',
      'Provide bright, filtered light to prevent leaf tips from burning',
      'Mist weekly or use a humidifier to keep foliage lush',
      'Protect from direct drafts and AC vents',
    ],
    height: '2.0 – 4.0 ft',
    difficulty: 'Medium',
    petFriendly: 'Yes',
    airPurifying: 'High',
  },
  {
    id: 14,
    name: 'Ficus Lyrata',
    scientificName: 'Ficus lyrata',
    category: 'Indoor Plants',
    price: 1890,
    rating: 4.7,
    reviews: 105,
    image: '/images/plants/ficus-lyrata.jpg?v=2',
    description: 'Commonly known as the Fiddle Leaf Fig, this is a statement houseplant featuring massive, glossy violin-shaped leaves. An architectural beauty.',
    details: {
      light: 'Bright, indirect light',
      water: 'Moderate',
      humidity: 'Moderate',
      temperature: '65-80°F',
      soil: 'Fast-draining soil with active aeration',
    },
    sizes: ['Medium (2.5-3 ft)', 'Large (4-5 ft)'],
    careInstructions: [
      'Water thoroughly only when the top 2 inches of soil are dry',
      'Wipe leaves with a damp cloth monthly to clean off dust',
      'Rotate the pot 90 degrees every month to ensure even growth',
      'Avoid moving the plant around as it is sensitive to placement changes',
    ],
    height: '3.0 – 5.0 ft',
    difficulty: 'Medium',
    petFriendly: 'No',
    airPurifying: 'High',
  },
  {
    id: 15,
    name: 'Aglaonema Red',
    scientificName: 'Aglaonema Siam Aurora',
    category: 'Indoor Plants',
    price: 750,
    rating: 4.9,
    reviews: 94,
    image: '/images/plants/aglaonema-red.jpg',
    description: 'A striking houseplant featuring bright pink and emerald-red variegated foliage. Tolerant of low light, making it a perfect pop of color for desks.',
    details: {
      light: 'Low to bright, indirect light',
      water: 'Low to moderate',
      humidity: 'Average',
      temperature: '60-80°F',
      soil: 'Standard well-aerated potting mix',
    },
    sizes: ['Small (6-8 inch)', 'Medium (10-12 inch)'],
    careInstructions: [
      'Allow soil to dry out significantly between waterings',
      'Tolerant of lower lighting conditions, but colors are brightest in indirect light',
      'Fertilize twice a year during spring and summer',
      'Avoid cold drafts and keep in warm areas',
    ],
    height: '1.0 – 1.6 ft',
    difficulty: 'Easy',
    petFriendly: 'No',
    airPurifying: 'High',
  },
  {
    id: 16,
    name: 'Snake Plant',
    scientificName: 'Sansevieria trifasciata',
    category: 'Indoor Plants',
    price: 650,
    rating: 4.9,
    reviews: 215,
    image: '/images/plants/snake-plant.jpg',
    description: 'An exceptionally hardy plant with stiff, vertical sword-like leaves with yellow margins. Well-known for purifying indoor air and releasing oxygen at night.',
    details: {
      light: 'Low to full sun',
      water: 'Very low',
      humidity: 'Low',
      temperature: '55-85°F',
      soil: 'Cactus and succulent sandy compost',
    },
    sizes: ['Small (1 ft)', 'Medium (2 ft)'],
    careInstructions: [
      'Water only when soil is 100% bone-dry; water once every 3-4 weeks',
      'Tolerates low light environments but thrives in brighter areas',
      'Do not let water pool in the leaf rosettes',
      'Extremely durable—perfect for beginners',
    ],
    height: '1.0 – 3.0 ft',
    difficulty: 'Easy',
    petFriendly: 'No',
    airPurifying: 'High',
  },
  {
    id: 17,
    name: 'Premium Pruning Shears',
    scientificName: 'Tools & Accessories',
    category: 'Gardening Tools',
    price: 850,
    rating: 4.8,
    reviews: 64,
    image: '/images/plants/gardening-tools.png?v=2',
    description: 'Heavy duty, rust-resistant bypass pruning shears. Features ergonomic grips and sharp carbon steel blades for clean cuts.',
    details: {
      light: 'N/A',
      water: 'Keep dry after use',
      humidity: 'Low',
      temperature: 'N/A',
      soil: 'N/A',
    },
    sizes: ['Standard 8" Shears'],
    careInstructions: [
      'Wipe blades clean of sap and dirt after every session',
      'Oil the spring mechanism and joint monthly for smooth operation',
      'Lock blades closed when not in use',
      'Keep away from moisture to prevent oxidation',
    ],
    height: 'N/A',
    difficulty: 'Easy',
    petFriendly: 'Yes',
    airPurifying: 'None',
  },
  {
    id: 18,
    name: 'Brass Watering Can',
    scientificName: 'Tools & Accessories',
    category: 'Gardening Tools',
    price: 1550,
    rating: 4.9,
    reviews: 78,
    image: '/images/plants/watering-can.jpg',
    description: 'An elegant solid brass watering can with a long, slender gooseneck spout for precise watering. Double-coated to prevent tarnishing.',
    details: {
      light: 'N/A',
      water: 'N/A',
      humidity: 'N/A',
      temperature: 'N/A',
      soil: 'N/A',
    },
    sizes: ['1.0 Liter Capacity'],
    careInstructions: [
      'Empty unused water after each watering session',
      'Wipe outer surface with a dry microfibre cloth to maintain shine',
      'Do not use harsh chemical polishes on the protective coat',
    ],
    height: 'N/A',
    difficulty: 'Easy',
    petFriendly: 'Yes',
    airPurifying: 'None',
  },
  {
    id: 19,
    name: 'Neem Oil Pest Spray',
    scientificName: 'Organic Plant Protection',
    category: 'Plants Medicine',
    price: 350,
    rating: 4.7,
    reviews: 53,
    image: '/images/plants/neem-oil.jpg',
    description: 'A 100% natural, ready-to-use organic neem oil spray. Safely repels common garden pests including spider mites, aphids, and whiteflies.',
    details: {
      light: 'Store in cool, dark place',
      water: 'Use as foliar spray',
      humidity: 'N/A',
      temperature: '60-80°F (storage)',
      soil: 'N/A',
    },
    sizes: ['500ml Spray Bottle'],
    careInstructions: [
      'Shake bottle thoroughly before spraying',
      'Spray plant leaves evenly, covering both top and bottom surfaces',
      'Apply early in the morning or in evening to avoid leaf burn in the sun',
      'Repeat application every 7-14 days for effective pest control',
    ],
    height: 'N/A',
    difficulty: 'Easy',
    petFriendly: 'Yes',
    airPurifying: 'None',
  },
  {
    id: 20,
    name: 'Bio-Organic Fertilizer',
    scientificName: 'Organic Soil Nutrients',
    category: 'Organic Fertilizer',
    price: 490,
    rating: 4.9,
    reviews: 82,
    image: '/images/plants/organic-fertilizer.png?v=2',
    description: 'A premium liquid organic concentrate enriched with micronutrients. Enhances root growth, foliage color, and soil microbiology.',
    details: {
      light: 'Store away from direct light',
      water: 'Dilute in water',
      humidity: 'N/A',
      temperature: '50-85°F',
      soil: 'Improves soil biology',
    },
    sizes: ['250ml Concentrate Bottle'],
    careInstructions: [
      'Dilute 5ml of concentrate in 1 Liter of water',
      'Water plants with the solution once every 2 weeks during active growth',
      'Do not apply directly to dry soil; moisten soil slightly first',
      'Store bottle tightly closed out of reach of children',
    ],
    height: 'N/A',
    difficulty: 'Easy',
    petFriendly: 'Yes',
    airPurifying: 'None',
  },
  {
    id: 21,
    name: 'Lucky Bamboo Spiral',
    scientificName: 'Dracaena sanderiana',
    category: 'Lucky Bamboo',
    price: 350,
    rating: 4.8,
    reviews: 74,
    image: '/images/plants/lucky-bamboo.png?v=2',
    description: 'A classic indoor water plant representing good fortune and prosperity. Features elegant spiral stems arranged in a clean glass vase with pebbles.',
    details: {
      light: 'Low to moderate indirect light',
      water: 'Change water weekly; keep roots submerged',
      humidity: 'Average',
      temperature: '65-90°F',
      soil: 'Water culture / Pebbles',
    },
    sizes: ['Standard Glass Vase'],
    careInstructions: [
      'Change water every 7-10 days with filtered water',
      'Avoid placing in direct hot sunlight to prevent leaf yellowing',
      'Keep roots fully submerged',
      'Add a drop of liquid fertilizer monthly'
    ],
    height: '1.0 – 1.5 ft',
    difficulty: 'Easy',
    petFriendly: 'No',
    airPurifying: 'Moderate',
  },
  {
    id: 22,
    name: 'Classic Terracotta Clay Pot',
    scientificName: 'Garden Accessory',
    category: 'No1. Clay Pots',
    price: 150,
    rating: 4.7,
    reviews: 43,
    image: '/images/plants/clay-pots.png?v=2',
    description: 'A traditional breathable clay pot, perfect for healthy plant roots and prevention of root rot.',
    details: {
      light: 'N/A',
      water: 'N/A',
      humidity: 'N/A',
      temperature: 'N/A',
      soil: 'N/A',
    },
    sizes: ['6 inch Pot', '8 inch Pot', '10 inch Pot'],
    careInstructions: [
      'Soak pot in water before planting for the first time',
      'Clean occasionally with mild soapy water to remove salt deposits',
      'Handle with care to avoid cracking'
    ],
    height: 'N/A',
    difficulty: 'Easy',
    petFriendly: 'Yes',
    airPurifying: 'None',
  },
  {
    id: 23,
    name: 'Premium Fiber Planter',
    scientificName: 'Garden Accessory',
    category: 'No1. Fiber Pots',
    price: 599,
    rating: 4.9,
    reviews: 31,
    image: '/images/plants/fiber-pots.png?v=2',
    description: 'A lightweight and durable fiberglass pot with a modern minimalist texture, ideal for indoor styling.',
    details: {
      light: 'N/A',
      water: 'N/A',
      humidity: 'N/A',
      temperature: 'N/A',
      soil: 'N/A',
    },
    sizes: ['10 inch Planter', '12 inch Planter'],
    careInstructions: [
      'Wipe with a damp cloth to clean dust',
      'Designed with drainage hole at bottom',
      'Extremely lightweight and weather-resistant'
    ],
    height: 'N/A',
    difficulty: 'Easy',
    petFriendly: 'Yes',
    airPurifying: 'None',
  },
  {
    id: 24,
    name: 'Glazed Ceramic Planter',
    scientificName: 'Garden Accessory',
    category: 'Ceramic Pots',
    price: 450,
    rating: 4.8,
    reviews: 57,
    image: '/images/plants/ceramic-pots.png?v=2',
    description: 'An elegant glazed ceramic pot with unique handcrafted marbling patterns to elevate your tabletop plants.',
    details: {
      light: 'N/A',
      water: 'N/A',
      humidity: 'N/A',
      temperature: 'N/A',
      soil: 'N/A',
    },
    sizes: ['5 inch Pot', '7 inch Pot'],
    careInstructions: [
      'Wipe outer surface to maintain glossy shine',
      'Includes matching drainage tray',
      'Best for indoor tabletop succulents and indoor plants'
    ],
    height: 'N/A',
    difficulty: 'Easy',
    petFriendly: 'Yes',
    airPurifying: 'None',
  },
  {
    id: 25,
    name: 'Self-Watering Plastic Pot',
    scientificName: 'Garden Accessory',
    category: 'Plastic Pots',
    price: 199,
    rating: 4.6,
    reviews: 84,
    image: '/images/plants/plastic-pots.png?v=2',
    description: 'A premium quality UV-resistant plastic pot featuring an intelligent self-watering drainage mechanism.',
    details: {
      light: 'N/A',
      water: 'Self-watering system',
      humidity: 'N/A',
      temperature: 'N/A',
      soil: 'N/A',
    },
    sizes: ['Small (6 inch)', 'Medium (8 inch)'],
    careInstructions: [
      'Fill reservoir at bottom once every 2-3 weeks',
      'Ensure inner pot sits correctly on the base',
      'UV stabilized plastic prevents fading in sun'
    ],
    height: 'N/A',
    difficulty: 'Easy',
    petFriendly: 'Yes',
    airPurifying: 'None',
  },
  {
    id: 26,
    name: 'Sweet Mango Grafted Plant',
    scientificName: 'Mangifera indica',
    category: 'Fruit Plants',
    price: 350,
    rating: 4.8,
    reviews: 62,
    image: '/images/plants/fruit-plant.jpg',
    description: 'A high-yielding premium grafted mango plant suitable for terrace gardens and backyard growing. Produces delicious sweet mangoes.',
    details: {
      light: 'Full direct sunlight (6+ hours)',
      water: 'Moderate, moist well-draining soil',
      humidity: 'Moderate',
      temperature: '70-95°F',
      soil: 'Loamy, organic-rich soil',
    },
    sizes: ['Grafted Sapling (1.5-2 ft)'],
    careInstructions: [
      'Place in location with full direct sun',
      'Water when top soil feels dry, do not overwater',
      'Feed with organic fertilizer during growing season',
      'Protect from strong frost and freezing temperatures'
    ],
    height: '1.5 – 2.5 ft sapling',
    difficulty: 'Medium',
    petFriendly: 'Yes',
    airPurifying: 'Low',
  },
]
