export interface ProductCare {
  light: string
  water: string
  humidity: string
  temperature: string
  soil: string
}

export interface Product {
  id: number
  name: string
  category: string
  price: number // Numeric for sorting and math calculations (INR Rupees)
  rating: number
  reviews: number
  image: string
  description: string
  details: ProductCare
  sizes: string[]
  careInstructions: string[]
}

export const allProducts: Product[] = [
  {
    id: 1,
    name: 'Monstera Deliciosa',
    category: 'Indoor Plants',
    price: 1499,
    rating: 4.8,
    reviews: 128,
    image: '/images/plants/monstera-plant.jpg',
    description: 'The iconic Monstera Deliciosa, also known as the Swiss Cheese Plant, is a stunning tropical plant perfect for any indoor space. Known for its distinctive split leaves and climbing nature.',
    details: {
      light: 'Bright, indirect light',
      water: 'Water when soil is dry',
      humidity: 'Moderate to high',
      temperature: '65-75°F',
      soil: 'Well-draining potting soil',
    },
    sizes: ['Small (6-8 inch)', 'Medium (10-12 inch)', 'Large (14-16 inch)'],
    careInstructions: [
      'Allow top inch of soil to dry between waterings',
      'Provide bright, indirect light',
      'Wipe leaves monthly with soft cloth',
      'Fertilize monthly during growing season',
      'Support with moss pole as plant grows',
    ],
  },
  {
    id: 2,
    name: 'Peace Lily',
    category: 'Air Purifying',
    price: 599,
    rating: 4.9,
    reviews: 156,
    image: '/images/plants/peace-lily.jpg',
    description: 'Peace Lilies are famous for their air-purifying abilities and elegant white blooms. They are resilient, low-maintenance plants that tell you when they are thirsty by drooping their leaves.',
    details: {
      light: 'Low to medium light',
      water: 'Keep soil consistently moist',
      humidity: 'High humidity preferred',
      temperature: '60-80°F',
      soil: 'Peat-rich, well-draining soil',
    },
    sizes: ['Small (5-7 inch)', 'Medium (8-10 inch)'],
    careInstructions: [
      'Water when leaves begin to droop slightly',
      'Keep away from direct sunlight to avoid leaf burn',
      'Mist the leaves regularly to maintain humidity',
      'Prune yellow or brown leaves at the base',
    ],
  },
  {
    id: 3,
    name: 'Pothos Hanging',
    category: 'Indoor Plants',
    price: 399,
    rating: 4.7,
    reviews: 92,
    image: '/images/plants/pothos-hanging.jpg',
    description: 'Pothos is one of the easiest house plants to grow. Its beautiful trailing vines look stunning cascading from hanging baskets or shelves, featuring heart-shaped leaves.',
    details: {
      light: 'Low to bright, indirect light',
      water: 'Water when top 2 inches of soil are dry',
      humidity: 'Average indoor humidity',
      temperature: '60-85°F',
      soil: 'Standard potting mix',
    },
    sizes: ['Small basket (6 inch)', 'Medium basket (8 inch)'],
    careInstructions: [
      'Allow soil to dry out between waterings to prevent root rot',
      'Trim vines to encourage fuller growth at the top',
      'Can survive in low light, but variegated patterns fade',
      'Propagates easily in water from stem cuttings',
    ],
  },
  {
    id: 4,
    name: 'Succulent Collection',
    category: 'Succulents',
    price: 299,
    rating: 4.9,
    reviews: 203,
    image: '/images/plants/succulent-collection.jpg',
    description: 'A curated collection of beautiful, hardy succulents. Perfect for sunny windowsills, desktops, or as a lovely gift. These desert natives store water in their leaves and require very little care.',
    details: {
      light: 'Direct, bright sunlight',
      water: 'Water sparingly, only when completely dry',
      humidity: 'Low/dry air',
      temperature: '55-80°F',
      soil: 'Cactus/Succulent sandy mix',
    },
    sizes: ['Set of 3 (2 inch pots)', 'Set of 6 (2 inch pots)'],
    careInstructions: [
      'Water using the soak and dry method; do not let water sit in the tray',
      'Provide at least 6 hours of bright sunlight daily',
      'Ensure pots have drainage holes',
      'Protect from freezing temperatures',
    ],
  },
  {
    id: 5,
    name: 'Red Roses Bouquet',
    category: 'Flowers',
    price: 699,
    rating: 4.8,
    reviews: 178,
    image: '/images/plants/rose-flowers.jpg',
    description: 'A classic and stunning arrangement of premium long-stemmed red roses. Perfect for celebrating special occasions, anniversaries, or expressing love. Freshly cut and arranged with elegant greenery.',
    details: {
      light: 'Bright room, avoid direct hot sun',
      water: 'Keep vase water clean and cool',
      humidity: 'Moderate',
      temperature: '60-70°F',
      soil: 'Cut flowers (N/A)',
    },
    sizes: ['Standard (12 stems)', 'Premium (24 stems)'],
    careInstructions: [
      'Trim stems at a 45-degree angle before placing in water',
      'Change water every 2 days and add flower food',
      'Remove any leaves that fall below the water line',
      'Keep away from drafts, direct heat, and ripening fruit',
    ],
  },
  {
    id: 6,
    name: 'Lavender Plant',
    category: 'Herbs',
    price: 499,
    rating: 4.6,
    reviews: 67,
    image: '/images/plants/lavender-plant.jpg',
    description: 'Lavender is beloved for its beautiful purple blooms and relaxing, aromatic fragrance. Excellent for herb gardens, sunny patios, or placing near windows to enjoy its calming scent.',
    details: {
      light: 'Full, direct sun (6+ hours)',
      water: 'Water deeply but infrequently; drought-tolerant',
      humidity: 'Low humidity',
      temperature: '50-80°F',
      soil: 'Well-draining, alkaline soil',
    },
    sizes: ['Medium (6 inch pot)', 'Large (8 inch pot)'],
    careInstructions: [
      'Avoid overwatering; let soil dry completely between waterings',
      'Prune in early spring to maintain shape and promote blooms',
      'Ensure excellent drainage to prevent root rot',
      'Harvest flowers just as they start to open for the best fragrance',
    ],
  },
  {
    id: 7,
    name: 'Orchid Flower',
    category: 'Flowers',
    price: 999,
    rating: 4.7,
    reviews: 145,
    image: '/images/plants/orchid-flower.jpg',
    description: 'Exotic and elegant, this Phalaenopsis orchid displays stunning moth-like blooms that can last for months. A perfect statement piece for dining tables or office desks.',
    details: {
      light: 'Bright, indirect light',
      water: 'Water every 7-10 days, allowing bark to dry',
      humidity: 'High humidity (50-70%)',
      temperature: '65-80°F',
      soil: 'Sphagnum moss or orchid bark mix',
    },
    sizes: ['Standard (Single Spike)', 'Premium (Double Spike)'],
    careInstructions: [
      'Do not let the roots sit in standing water',
      'Mist the air around the orchid or use a humidity tray',
      'Fertilize weekly at weak strength during active growth',
      'Cut the spike back to a node once blooms fade to encourage reblooming',
    ],
  },
  {
    id: 8,
    name: 'Bonsai Tree',
    category: 'Specialty',
    price: 2499,
    rating: 4.8,
    reviews: 89,
    image: '/images/plants/bonsai-tree.jpg',
    description: 'A beautiful miniature Juniper Bonsai tree, carefully shaped to represent harmony and balance. An ancient art form that brings peace and mindful energy to any living space.',
    details: {
      light: 'Bright, indirect light; thrives outdoors too',
      water: 'Keep soil moist; do not let dry out completely',
      humidity: 'Moderate to high',
      temperature: '50-75°F',
      soil: 'Special Bonsai fast-draining soil mix',
    },
    sizes: ['Small (5 years old)', 'Medium (8 years old)'],
    careInstructions: [
      'Check moisture daily; water thoroughly when top soil feels dry',
      'Prune new growth regularly to maintain the bonsai shape',
      'Repot every 2-3 years in late spring',
      'Provide outdoor fresh air occasionally if kept indoors',
    ],
  },
  {
    id: 9,
    name: 'Tulips Bouquet',
    category: 'Flowers',
    price: 899,
    rating: 4.9,
    reviews: 234,
    image: '/images/plants/tulips-bouquet.jpg',
    description: 'A colorful and vibrant arrangement of fresh spring tulips. Symbolizing cheerfulness and renewal, this bouquet brings instant brightness and joy to any room.',
    details: {
      light: 'Bright room, avoid direct sun',
      water: 'Keep vase water clean and cool',
      humidity: 'Average',
      temperature: '55-65°F',
      soil: 'Cut flowers (N/A)',
    },
    sizes: ['Bouquet of 15', 'Bouquet of 30'],
    careInstructions: [
      'Trim stems slightly and place in cold water immediately',
      'Change water daily to keep flowers fresh',
      'Tulips continue to grow in the vase; trim again if they get too tall',
      'Keep away from warm appliances and direct sunlight',
    ],
  },
  {
    id: 10,
    name: 'Sunflower Garden',
    category: 'Flowers',
    price: 399,
    rating: 4.6,
    reviews: 76,
    image: '/images/plants/sunflower-garden.jpg',
    description: 'Bring the joy of summer indoors with these dwarf potted sunflowers. Featuring bright, cheerful yellow petals, they are guaranteed to make anyone smile and brighten up sunny spots.',
    details: {
      light: 'Full, direct sun (6-8 hours)',
      water: 'Water daily or when top soil feels dry',
      humidity: 'Average',
      temperature: '60-80°F',
      soil: 'Rich, well-draining compost',
    },
    sizes: ['Single Pot (6 inch)', 'Triple Pot Set'],
    careInstructions: [
      'Place in the sunniest window available',
      'Water at the base of the plant to avoid wet foliage',
      'Stake the stems if they start leaning towards the light',
      'Remove spent blooms to encourage new buds',
    ],
  },
  {
    id: 11,
    name: 'Dahlia Bouquet',
    category: 'Flowers',
    price: 799,
    rating: 4.7,
    reviews: 110,
    image: '/images/plants/dahlia-bouquet.jpg',
    description: 'A breathtaking bouquet of mixed dahlias, featuring intricate petal patterns and a rich spectrum of colors. Hand-picked and styled to create an exquisite centerpiece.',
    details: {
      light: 'Bright indirect light',
      water: 'Change vase water every 2 days',
      humidity: 'Moderate',
      temperature: '60-70°F',
      soil: 'Cut flowers (N/A)',
    },
    sizes: ['Standard Bouquet', 'Deluxe Bouquet'],
    careInstructions: [
      'Recut stems under water before putting in a clean vase',
      'Keep in a cool spot away from drafts',
      'Add floral preservative to the water',
      'Remove any wilted petals immediately',
    ],
  },
  {
    id: 12,
    name: 'Premium Orchid',
    category: 'Specialty',
    price: 1599,
    rating: 4.8,
    reviews: 98,
    image: '/images/plants/orchid-flower.jpg',
    description: 'An exquisite premium orchid selection featuring rare color patterns and exceptionally large blooms. Ideal for luxury gifting or as an upscale home decor addition.',
    details: {
      light: 'Filter bright, indirect light',
      water: 'Water weekly when roots look silver/grey',
      humidity: 'High (60%+)',
      temperature: '65-75°F',
      soil: 'Premium orchid bark medium',
    },
    sizes: ['Deluxe Single Spike', 'Grand Double Spike'],
    careInstructions: [
      'Ensure good air circulation around the roots',
      'Water by running water through the pot for 1 minute, then drain',
      'Use a specialized orchid fertilizer monthly',
      'Do not mist flowers directly to avoid spotting',
    ],
  },
]
